# Generated by Django 5.1.2 on 2025-03-27 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do tipo de eleição')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Eleição',
                'verbose_name_plural': 'Tipos de Eleição',
            },
        ),
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de término')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=15, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleicoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tipo_eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.tipoeleicao', verbose_name='Tipo de Eleição')),
            ],
            options={
                'verbose_name': 'Eleição',
                'verbose_name_plural': 'Eleições',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da chapa')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número da chapa')),
                ('slogan', models.CharField(max_length=200, verbose_name='Slogan')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='chapas/', verbose_name='Imagem')),
                ('propostas', models.TextField(verbose_name='Propostas')),
                ('presidente_nome', models.CharField(max_length=200, verbose_name='Nome do Presidente')),
                ('presidente_serie', models.CharField(max_length=50, verbose_name='Série/Turma do Presidente')),
                ('presidente_matricula', models.CharField(max_length=50, verbose_name='Matrícula do Presidente')),
                ('presidente_email', models.EmailField(max_length=254, verbose_name='Email do Presidente')),
                ('presidente_telefone', models.CharField(max_length=20, verbose_name='Telefone do Presidente')),
                ('vice_nome', models.CharField(max_length=200, verbose_name='Nome do Vice-Presidente')),
                ('vice_serie', models.CharField(max_length=50, verbose_name='Série/Turma do Vice-Presidente')),
                ('vice_matricula', models.CharField(max_length=50, verbose_name='Matrícula do Vice-Presidente')),
                ('vice_email', models.EmailField(max_length=254, verbose_name='Email do Vice-Presidente')),
                ('documento_assinaturas', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Documento de Assinaturas')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapas', to='election.eleicao', verbose_name='Eleição')),
            ],
            options={
                'verbose_name': 'Chapa',
                'verbose_name_plural': 'Chapas',
                'unique_together': {('eleicao', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='MembroChapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('serie', models.CharField(max_length=50, verbose_name='Série/Turma')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matrícula')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo na chapa')),
                ('chapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='election.chapa', verbose_name='Chapa')),
            ],
            options={
                'verbose_name': 'Membro da Chapa',
                'verbose_name_plural': 'Membros da Chapa',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_voto', models.DateTimeField(auto_now_add=True, verbose_name='Data do voto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('chapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='election.chapa', verbose_name='Chapa')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='election.eleicao', verbose_name='Eleição')),
                ('eleitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votos', to=settings.AUTH_USER_MODEL, verbose_name='Eleitor')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'unique_together': {('eleicao', 'eleitor')},
            },
        ),
    ]
