# Generated by Django 5.1.2 on 2025-03-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapa',
            name='vice_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Vice-Presidente'),
        ),
        migrations.AlterField(
            model_name='chapa',
            name='vice_matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula do Vice-Presidente'),
        ),
        migrations.AlterField(
            model_name='chapa',
            name='vice_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Vice-Presidente'),
        ),
        migrations.AlterField(
            model_name='chapa',
            name='vice_serie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Série/Turma do Vice-Presidente'),
        ),
    ]
